---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-mysql"
  labels:
    app: wordpress
spec:
  ports:
  - port: "{{ .Values.mysql.service.port }}"
    targetPort: "{{ .Values.mysql.service.port }}"
    protocol: "{{ .Values.mysql.service.protocol }}"
  selector:
    app: wordpress
    tier: mysql
  type: "{{ .Values.mysql.service.type }}"
  #Headless Service for Database
  #Key Differences- 
  #ClusterIP = single virtual IP with built-in load balancing across Pods.
  #Headless (clusterIP: None) = no virtual IP, DNS returns Pod IPs, client chooses Pod.
  clusterIP: None