---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-mysql"
  labels:
    app: wordpress
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: {{ .Values.mysql.service.port }}
    protocol: {{ .Values.mysql.service.protocol }}
  selector:
    app: wordpress
    tier: mysql
  type: {{ .Values.mysql.service.type }}