---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.mysql.persistence.claimName }}"
  labels:
    app: wordpress
    release: "{{ .Release.Name }}"
spec:
  accessModes:
  - "{{ .Values.mysql.persistence.accessMode }}"
  resources:
    requests:
      storage: "{{ .Values.mysql.persistence.size }}"
  storageClassName: "{{ .Values.mysql.persistence.storageClass }}"