---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.wordpress.persistence.claimName }}
  labels:
    app: wordpress
    chart: {{ include "wp-chart.chart" . }}
    release: {{ .Release.Name }}
spec:
  accessModes:
  - {{ .Values.wordpress.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}
  storageClassName: {{ .Values.wordpress.persistence.storageClass }}