---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-wordpress"
  labels:
    app: wordpress
    release: {{ .Release.Name }}
spec:
  #single virtual IP with built-in load balancing across Pods.
  type: {{ .Values.wordpress.service.type }}
  selector:
    app: wordpress
    tier: frontend
  ports:
  - port: {{ .Values.wordpress.service.port }}
    targetPort: {{ .Values.wordpress.service.port }}
    protocol: {{ .Values.wordpress.service.protocol }}