---
apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
    - name: myapp
      image: busybox
      command: ["sh", "-c", "echo $APP_MODE $TIMEOUT && sleep 3600"]
      envFrom:
        - configMapRef:
            name: app-config

