apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask
    namespace: barista
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: kubeutkarsh0911/flask-app:v1
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: barista-config
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: barista-secret
                  key: MYSQL_PASSWORD
    