---
apiVersion: v1
kind: Pod
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  containers:
    - name: appcontainer
      image: kubeutkarsh0911/vprofileapp:latest
      ports:
        - name: vproapp-port
          containerPort: 8080
