---
- name: Webserver Setup
  hosts: webservers
  become: yes
  tasks:
    #- name: Update cache
    #  ansible.builtin.apt:
    #    update_cache: yes

    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Start Service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

- name: DBServer Setup
  hosts: dbservers
  become: yes
  tasks:
    #- name: Update cache
    #  ansible.builtin.apt:
    #    update_cache: yes

    - name: Install mariadb-server
      ansible.builtin.apt:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB service is started and enabled
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

