---
- name: Understanding vars
  hosts: all
  become: yes
    #vars:
    #USRNM: playuser
    #COMM: "variable from playbook"
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{ USRNM }}"
        comment: "{{ COMM }}"
      register: usrout

    - name: Print usrout name
      debug:
        var: usrout.name
