#SPDX-License-Identifier: MIT-0
---
# tasks file for post-install
- name: Install ntp agent on ubuntu
  apt:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "Ubuntu"
  loop:
    - ntp
    - wget
    - git
    - zip
    - unzip

- name: Start and enable service on Ubuntu
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Banner file
  copy:
    content: '#This server is managed by ansible. No manual changes please.'
    dest: /etc/motd

- name: Create /etc/myapp directory
  ansible.builtin.file:
    path: /etc/myapp
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create a folder
  file:
    path: "{{ mydir}}"
    state: directory

- name: Deploy NTP configuration using template
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart NTP

- name: Dump files
  copy:
    src: myfile.txt
    dest: /tmp/myfile.txt
