---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: wordpress-pvc
  labels:
    app: wordpress
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: default