- debug:
    msg: "{{db_name}}"
- debug:
    msg: "{{db_user}}"
- debug:
    msg: "{{db_password}}"
- name: Install mariadb-server
  ansible.builtin.apt:
    name: mariadb-server
    state: present

- name: Ensure MariaDB service is started and enabled
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: Ensure Python MySQL library is installed
  ansible.builtin.apt:
    name: python3-mysqldb
    state: present

- name: Create database '{{ db_name }}'
  community.mysql.mysql_db:
    name: '{{ db_name }}'
    state: present

- name: Create database user '{{ db_user }}'
  community.mysql.mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    priv: '{{ db_name }}.*:ALL'
    state: present
  register: dbout

- name: Print dbout variable
  debug:
    var: dbout
